--------------------------------------------------------
--  DDL for Table MOVIELIST
--------------------------------------------------------

  CREATE TABLE "C##DBEXAM"."MOVIELIST" 
   (	"TITLEID" NUMBER(38,0), 
	"TITLE" VARCHAR2(317 BYTE), 
	"POSTER_PATH" VARCHAR2(269 BYTE), 
	"BUDGET" NUMBER(38,0), 
	"GENRESID" VARCHAR2(145 BYTE), 
	"GENRES" VARCHAR2(173 BYTE), 
	"COUNTRYID" VARCHAR2(181 BYTE), 
	"COUNTRY" VARCHAR2(629 BYTE), 
	"CHARACTORID" NUMBER(38,0), 
	"CHARACTOR" VARCHAR2(109 BYTE), 
	"DIRECTORID" NUMBER(38,0), 
	"DIRECTOR" VARCHAR2(129 BYTE), 
	"OVERVIEW" VARCHAR2(3977 BYTE), 
	"RUNTIME" NUMBER(38,0), 
	"RELEASE_DATE" DATE, 
	"VOTE_SCORE" NUMBER(38,3), 
	"VOTE_COUNT" NUMBER(38,0), 
	"VOTE_WEIGHT" NUMBER(38,15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
